name: Deploy to Heroku

on:
  push:
    branches:
      - main  # atau master, tergantung pada branch utama Anda

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "syspulse-websocket"  # ganti dengan nama app Heroku Anda
          heroku_email: ${{secrets.HEROKU_EMAIL}}